name: xllm_310yu
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - transformers
      - openai
      - pandas
      - einops
      - accelerate
      - sentencepiece
      - protobuf
      - transformers_stream_generator
      - tiktoken
      - autoawq
      - importlib-metadata
      - auto-gptq
      - sympy
      - llm
      - fastchat
      - numpy
     # - vllm
      - anthropic
      - google.generativeai
      - tqdm
